### PR TITLE
Indv solar disagg

### PR DESCRIPTION
**Pull request by bmeyers**
My understanding from @mtabone is that this is the most current version of the code base and should be what new users work with.

### CODE REVIEW

**Comment by bmeyers** [comment]
@eckara @mtabone please review and accept merge or provide feedback on necessary changes. If you decide to accept the merge, please delete other branches, so we can clone into the public GISMo Team repo. Once we've moved the repo, we can invite you if there's more work that you need to do.

**Comment by mtabone** [comment]
Hey Bennet.

May I do this on Saturday?

**Comment by bmeyers** [comment]
@mtabone absolutely

**Comment by eckara** [comment]
If MT approves so! ;) 

On Sun, Jul 22, 2018, at 5:36 PM, Michaelangelo Tabone wrote:
> Merged #11[1].


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].

Links:

  1. https://github.com/eckara/CSSS/pull/11
  2. https://github.com/eckara/CSSS/pull/11#event-1746642256

**Comment by mtabone** [comment]
Full disclosure, I didn't test any of the cross functionality. (I.e. ADMM
and SOlarDisagg). But I believe that the two should work separately in the
same package just fine.

**Comment by bmeyers** [comment]
Thanks @mtabone! Can you explain more what you mean by "cross functionality"? Is there more work to be done there?

**Comment by mtabone** [comment]
In general, Emre and I worked on separate functionalities:

   - Emre's branch worked with the general CSSS tool to include an ADMM
   method for solving the optimization as opposed to a general interior point
   method.
   - My branch developed wrapper functions around CSSS to more easily run
   solar disaggregation on individual homes.


The wrapper functions in my branch do not specifically utilize the ADMM
solver, and given the way that Emre implemented it initially (I'm not sure
if it's still like this) they cannot.

**Pull request merged**
